### ISSUE TITLE
404 Issue when running rebuild

### ISSUE THREAD

**Issue by jmathew1991** [carloslfu/figma-app-linux#3]
Hi. I'm pretty sure I've followed all the steps correctly, but I'm running into a 404 error when it tries to fetch node-v8.9.3-headers.tar.gz after running npm run electron-rebuild

```
npm run electron-rebuild
> figma-app-linux@0.0.2 electron-rebuild /home/jibin/Desktop/figma-app-linux
> electron-rebuild --parallel --force --types prod,dev,optional --module-dir app

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/electron/v8.9.3/node-v8.9.3-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/jibin/Desktop/figma-app-linux/node_modules/node-gyp/lib/install.js:214:14)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (/home/jibin/Desktop/figma-app-linux/node_modules/request/request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Linux 4.15.0-33-generic
gyp ERR! command "/home/jibin/.nvm/versions/node/v8.11.3/bin/node" "/home/jibin/Desktop/figma-app-linux/node_modules/.bin/node-gyp" "rebuild" "--target=2.0.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/jibin/Desktop/figma-app-linux/app/node_modules/font-manager
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1

```

**Comment by carloslfu** [comment]
Hi! In which OS are you working?

**Comment by dimoFeeld** [comment]
`sudo npm run electron-rebuild` fixed it for me
